# Generated by Django 3.0.7 on 2020-06-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Author', models.CharField(max_length=500)),
                ('VideoFile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
