# Generated by Django 3.0.7 on 2020-06-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0004_auto_20200628_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_list',
            name='pdf',
            field=models.FileField(upload_to='img-list'),
        ),
        migrations.AlterField(
            model_name='video_list',
            name='VideoFile',
            field=models.FileField(null=True, upload_to='videos-list/', verbose_name=''),
        ),
    ]
