# Generated by Django 3.0.7 on 2020-07-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Multimedia', '0006_auto_20200630_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('File_f', models.FileField(upload_to='post-media/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
